# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e3be8e492afb35b373c12f5839e209e4bef744b39860943191c5985154e9ba6a414b23004e2ebe1f9df49edbdd3853f7a41f8ee57deabd7d5b7dfa7d5fcfb82

test:
  secret_key_base: c6998614e064f431c0d96e382ba237cd3188409e2f0b7734becb6ea6bc31f89a55cd34132ed88af628014bc0d50bbeb844d3314d108aa49cf95dbb17aab920ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
